{% set name = "tornado-sqlalchemy" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f37e59c376aa7661beb96992977c64e6b0baf5cbe74c41ccc0bf3b25dee0e637

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - poetry
    - python >=3.5
  run:
    - python >=3.5
    - sqlalchemy >=1.3
    - tornado >=6.0

test:
  imports:
    - tornado_sqlalchemy

about:
  home: https://github.com/siddhantgoel/tornado-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: SQLAlchemy helpers for working in Tornado
  doc_url: https://tornado-sqlalchemy.readthedocs.io/
  dev_url: https://github.com/siddhantgoel/tornado-sqlalchemy

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
